//Write a program to print hello world.

#include<iostream.h>
#include<conio.h>

/*
   Pre-Processor Directives

   #-Pre Processor
   include- directive
   iostream.h - input/output stream/flow of data
   conio.h - Console input/output
*/

void main() // void/empty/null-no return type, main() - predefined function - entry point
{
  clrscr(); // clear screen
  cout<<"Hello World"; //cout - print output on console screen
  getch(); // get character
}

// Single line comment

/*
   Multiple line comment

*/